name: GitHub Actions Demo
run-name: ${{ github.actor }} Test GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    env:
      working-directory: ./electron
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: npm install
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: npm run deploy:mac
        working-directory: ${{ env.working-directory }}

